
version: "3.7"

volumes:
  workingdir: 
    driver: local

services:
  atx-cloud:
    container_name: atx-cloud
    working_dir: /atx-cloud-bin
    networks:
        - atx-cloud
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    ports:
      - 5000:5000
    #restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/../:/atx-cloud-bin
      - /home/ubuntu/mariadb/data/dbpopulation:/data/dbpopulation
      - /home/ubuntu/apiData/public:/home/ubuntu/apiData
      - /home/ubuntu/atx-spa-dist/dist:/home/ubuntu/atx-spa-dist/dist
      - /home/ubuntu/app_data:/home/ubuntu/app_data
    environment:
      - TZ=America/New_York
    command: uwsgi --http 0.0.0.0:5000 --module main:app

  atx-cloud-test:
    container_name: atx-cloud-test
    working_dir: /atx-cloud-bin
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    ports:
      - 5001:5000
    #restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/../:/atx-cloud-bin
      - $PWD/../../:/atx-cloud-data
      - /home/ubuntu/mariadb/data/dbpopulation:/data/dbpopulation
    environment:
      - TZ=America/New_York
    #command: uwsgi --http 0.0.0.0:4001 --module main:app
    command: python3 main.py --config "config_test.yml"

networks:
  atx-cloud:
    external: true

